name: "Linting and unit tests"

on:
  workflow_dispatch:
  push:
    branches: ['develop', 'master']
  pull_request:
    branches: ['develop', 'master']

jobs:
  lint:
    name: "PHP CodeSniffer (WordPress Coding Standards)"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, mysqlnd
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install WordPress Coding Standards
        run: |
          composer config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer require --dev wp-coding-standards/wpcs:"^3.0"
          composer require --dev phpcompatibility/phpcompatibility-paragonie:"^1.10"
          composer require --dev phpcompatibility/phpcompatibility-wp:"^2.2"
          composer require --dev phpcsstandards/phpcsutils:"^1.0"
          composer require --dev phpcsstandards/phpcsextra:"^1.0"
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs,~/.composer/vendor/phpcompatibility/phpcompatibility-wp,~/.composer/vendor/phpcompatibility/phpcompatibility-paragonie,~/.composer/vendor/phpcsstandards/phpcsutils,~/.composer/vendor/phpcsstandards/phpcsextra

      - name: Run PHP CodeSniffer
        run: |
          phpcs --version
          phpcs -i
          phpcs --standard=WordPress --extensions=php --ignore=*/vendor/*,*/node_modules/*,*/tests/*,*/post-types/* .
