name: "Create Release Package"

on:
  push:
    tags:
      - '*'  # Triggers on any tag push

jobs:
  build-release:
    name: "Build Release Package"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-dev

      - name: Create Release Zip
        run: |
          ZIP_NAME="accredible-certificates-${GITHUB_REF#refs/tags/v}.zip"
          zip -r "$ZIP_NAME" . -x "*.git*" -x "*.github*" -x "*.svnignore" -x ".actignore" -x "*.log" -x ".DS_Store" -x "tests/*" -x ".phpunit.result.cache" -x "phpunit.xml.dist" -x "coverage/*" -x "tmp/*" -x "Dockerfile" -x "docker-compose.yml"
          echo "ZIP_FILE=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
